---
dataset_root_dir: "C:\\data\\test_data\\Brazilian_E_Commerce"
source_file:
  orders:
    format: csv
    dataset: olist_orders_dataset.csv
    columns:
      - order_id
      - order_purchase_timestamp
      - order_status
    filters: "order_status not in ('canceled')"
  products:
    format: csv
    dataset: olist_products_dataset.csv
    columns:
      - product_id
      - product_category_name
    filters: "product_category_name is not null"
  order_payment:
    format: csv
    dataset: olist_order_payments_dataset.csv
    columns:
      - order_id
      - payment_value
  order_items:
    format: csv
    dataset: olist_order_items_dataset.csv
    columns:
      - order_id
      - product_id

countries:
  - brazil
